"""
This module defines the coding agents, their personalities, and the logic for generating solutions.
"""

import json
from dataclasses import dataclass
from typing import List, TypedDict, Optional

from llm_client import BaseLLMClient


# --- Data Structures ---

class AgentSolution(TypedDict):
    """A structured dictionary representing a solution generated by an agent."""
    thinking: str
    approach_name: str
    time_complexity: str
    space_complexity: str
    code: str
    error: Optional[str]


@dataclass
class AgentPersonality:
    """Dataclass to hold the defining traits of a coding agent."""
    name: str
    color: str
    system_prompt: str


# --- Agent Personalities Definitions ---

RECURSIVE_REX = AgentPersonality(
    name="RecursiveRex",
    color="#3498db",
    system_prompt="You are RecursiveRex, a coding agent that solves problems using recursion, divide-and-conquer, and memoization. Always break down problems into smaller, self-similar subproblems."
)

DYNAMIC_DANA = AgentPersonality(
    name="DynamicDana",
    color="#2ecc71",
    system_prompt="You are DynamicDana, a coding agent that loves dynamic programming. You solve problems by identifying subproblems and finding recurrence relations to build solutions from the bottom up using tabulation."
)

GREEDY_GUS = AgentPersonality(
    name="GreedyGus",
    color="#e74c3c",
    system_prompt="You are GreedyGus, a coding agent who believes in making the locally optimal choice at each step. You prefer simple, efficient iterative solutions, often using single-pass algorithms or two-pointer techniques."
)

DATA_STRUCT_DAVE = AgentPersonality(
    name="DataStructDave",
    color="#9b59b6",
    system_prompt="You are DataStructDave, a coding agent who focuses on choosing the perfect data structure for the job. You leverage hashmaps, heaps, trees, and other clever data structures to solve problems efficiently."
)

ALL_AGENTS: List[AgentPersonality] = [RECURSIVE_REX, DYNAMIC_DANA, GREEDY_GUS, DATA_STRUCT_DAVE]


# --- Coding Agent Class ---

class CodingAgent:
    """
    Represents a coding agent with a specific personality that can generate solutions.
    """
    def __init__(self, personality: AgentPersonality, llm_client: BaseLLMClient):
        self.personality = personality
        self.llm_client = llm_client

    def _create_prompt(self, problem: dict) -> str:
        """Creates the full prompt to be sent to the LLM."""
        return f"""
The user wants you to solve the following programming problem:

**Title:** {problem['title']}
**Description:** {problem['description']}
**Function Signature:** `{problem['function_signature']}`
**Constraints:**
- {', '.join(problem['constraints'])}

Please provide a solution in Python.

Your response MUST be a JSON object with the following structure:
{{
  "thinking": "Your thought process on how you arrived at the solution, following your personality.",
  "approach_name": "A concise name for your approach (e.g., 'Recursive with Memoization').",
  "time_complexity": "The Big O time complexity of your solution (e.g., 'O(n)').",
  "space_complexity": "The Big O space complexity of your solution (e.g., 'O(n)').",
  "code": "The complete, correct, and runnable Python code for the solution, fitting the function signature."
}}

Ensure your code is well-commented, especially where it reflects your specific algorithmic approach.
Do not include any extra text or explanation outside of the JSON object.
"""

    def _extract_json(self, response_text: str) -> dict:
        """
        Robustly extracts a JSON object from a string that might contain extra text.
        Finds the first '{' and the last '}' to bound the JSON object.
        """
        try:
            start_index = response_text.find('{')
            end_index = response_text.rfind('}')
            if start_index != -1 and end_index != -1 and start_index < end_index:
                json_str = response_text[start_index:end_index + 1]
                return json.loads(json_str)
            else:
                raise ValueError("No valid JSON object found in the response.")
        except (json.JSONDecodeError, ValueError) as e:
            # Fallback for when the LLM just returns code without the JSON structure
            code_keywords = ["def ", "class ", "import ", "from "]
            if any(keyword in response_text for keyword in code_keywords):
                 return {
                    "thinking": "Could not parse JSON from LLM response. Extracted code block as a fallback.",
                    "approach_name": "Unknown",
                    "time_complexity": "Unknown",
                    "space_complexity": "Unknown",
                    "code": response_text
                }
            raise ValueError(f"Failed to decode JSON from LLM response: {e}\\nResponse: {response_text}") from e

    def generate_solution(self, problem: dict) -> AgentSolution:
        """
        Generates a solution for the given problem based on the agent's personality.
        Handles JSON extraction and validation.
        """
        prompt = self._create_prompt(problem)
        try:
            raw_response = self.llm_client.generate(prompt, self.personality.system_prompt, temperature=0.5)
            parsed_json = self._extract_json(raw_response)

            required_keys = {"thinking", "approach_name", "time_complexity", "space_complexity", "code"}
            if not required_keys.issubset(parsed_json.keys()):
                raise ValueError(f"LLM response is missing one or more required keys: {required_keys - set(parsed_json.keys())}")

            code = parsed_json["code"]
            # Clean up potential markdown formatting from the code block
            if "```python" in code:
                code = code.split("```python")[1]
            if "```" in code:
                code = code.split("```")[0]

            solution: AgentSolution = {
                "thinking": parsed_json["thinking"],
                "approach_name": parsed_json["approach_name"],
                "time_complexity": parsed_json["time_complexity"],
                "space_complexity": parsed_json["space_complexity"],
                "code": code.strip(),
                "error": None
            }
            return solution

        except (ValueError, RuntimeError) as e:
            error_message = f"Agent {self.personality.name} failed to generate a valid solution. Error: {e}"
            return {
                "thinking": error_message,
                "approach_name": "Error",
                "time_complexity": "N/A",
                "space_complexity": "N/A",
                "code": f"# Generation failed.\n",
                "error": error_message
            }
